wip

diff --git a/.github/workflows/trigger_jenkins.yaml b/.github/workflows/trigger_jenkins.yaml
--- a/.github/workflows/trigger_jenkins.yaml
+++ b/.github/workflows/trigger_jenkins.yaml
@@ -1,4 +1,4 @@
-name: Trigger next gating
+name: Trigger Jenkins Job
 
 on:
   push:
@@ -9,29 +9,30 @@ jobs:
   trigger-jenkins:
     runs-on: ubuntu-latest
     steps:
-      - name: Dump GitHub context
+      - name: Trigger Jenkins Job
         env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: echo "$GITHUB_CONTEXT"
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Start Jenkins Job
-        uses: scylladb-actions/jenkins-client@v0.2.0
-        with:
-          job_name: 'releng-testing/job/ami'
-          jenkins_job_parameters: '{"APP_ENV_NAME": "staging"}'
-          base_url: https://jenkins.scylladb.com
-          user: 'yaronkaikov'
-          password: ${{ secrets.JENKINS_TOKEN }}
-
-      - name: Notify Slack on Failure
-        if: failure()
+          JENKINS_USER: 'yaronkaikov'
+          JENKINS_API_TOKEN: ${{ secrets.JENKINS_TOKEN }}
+          JENKINS_URL: "https://jenkins.scylladb.com"
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+          JOB_NAME: "releng-testing/job/ami"
         run: |
-          echo "Action failed, sending Slack alert..."
-          curl -X POST -H 'Content-type: application/json' \
-            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
-            --data '{
-              "channel": "#sandbox-channel",
-              "text": "🚨 @here '${{ env.JOB_NAME }}' failed to be triggered, please check https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for more details."
-            }' \
-            https://slack.com/api/chat.postMessage
+          echo "Triggering Jenkins Job: $JOB_NAME"
+          if ! curl -X POST "$JENKINS_URL/job/$JOB_NAME/buildWithParameters" --fail --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
+              --data-urlencode "RELENG_REPO=git@github.com:${{ github.repository }}.git" \
+              --data-urlencode "RELENG_BRANCH=${{ github.ref}}" \
+              -i -v; then
+            echo "Error: Jenkins job trigger failed"
+
+            # Send Slack message
+            curl -X POST -H 'Content-type: application/json' \
+              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
+              --data '{
+                "channel": "#jenkins-notifications",
+                "text": "🚨 Jenkins job *'$JOB_NAME'* failed!",
+                "icon_emoji": ":warning:"
+              }' \
+              https://slack.com/api/chat.postMessage
+
+            exit 1
+          fi
